.TH AUR-FETCH-SNAPSHOT 1 2018-02-14 AURUTILS
.SH NAME
aur-fetch-snapshot \- fetches a tar archive from a given URL.

.SH SYNOPSIS
.SY aur
.B fetch-snapshot
.OP -L log_dir 
.YS

.SH DESCRIPTION
\fBaur-fetch-snapshot\fR accepts URLs from stdin, and attempts to
download and extract tar archives to a given location.

.SH OPTIONS
.B \-L
.RS
The location of where the package should be downloaded.
.RE

.SH SEE ALSO
.BR tar (1),
.BR aur-fetch (1),
.BR aur (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
