#!/bin/bash
# aur-vercmp - check packages for AUR updates
set -o pipefail
readonly argv0=version
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

aur rpc -t info | jq -r '.results[] | [.Name, .Version] | @tsv'
