#!/bin/bash
# aur-fetch - retrieve build files from the AUR
readonly argv0=fetch
readonly AUR_LOCATION=${AUR_LOCATION:-'https://aur.archlinux.org'}
readonly fmt_git_clone=$AUR_LOCATION/%s.git
readonly fmt_snapshot=$AUR_LOCATION/cgit/aur.git/snapshot/%s.tar.gz
readonly startdir=$PWD
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options
log=directory mode=git recurse=0

git_stat_patch() {
    git --no-pager log -O "$1" --patch --stat '..@{upstream}'
}

upstream_sync() {
    local orderfile=${GIT_DIR:-$PWD/.git}/orderfile

    # default to showing PKGBUILD in diffs first (#399)
    if [[ ! -s $orderfile ]]; then
        echo PKGBUILD >"$orderfile"
    fi

    # get last upstream revision
    git fetch -v >&2

    if [[ $(git rev-parse HEAD) != $(git rev-parse '@{upstream}') ]]; then
	# only print log on upstream changes
	if [[ -f $1 ]]; then
            git_stat_patch "$orderfile" >> "$1"
	else
	    git_stat_patch "$orderfile"
	fi

        # discard any local changes (#349)
        git reset --hard "HEAD@{upstream}" >&2
    fi
}

fetch_git() {
    local uri pkg output

    while IFS= read -r uri; do
        pkg=${uri##*/}   # strip path
        pkg=${pkg%%.git} # strip .git suffix

        if [[ -d $1 ]]; then
            output=$1/$pkg.patch
	else
	    output=
        fi

        if [[ -d $pkg/.git ]]; then
            # avoid issues with filesystem boundaries (#274)
            GIT_DIR="$PWD/$pkg"/.git GIT_WORK_TREE="$PWD/$pkg" upstream_sync "$pkg" "$output"
        else
            git clone "$uri"
        fi
    done
}

tar_no_mode_diff() {
    if [[ -d $1/$2 ]]; then
        LC_MESSAGES=C tar -df "$3" -C "$1" | grep -Evq '(Mode|Uid|Gid)'
    else
        return 1
    fi
}

diff_log() {
    tee -a "$1/$2".diff | diffstat -Ckq -f3
}

fetch_tar() {
    #global tmp
    local archive base

    wget -i /dev/stdin --directory-prefix "$tmp" || return 1

    for archive in "$tmp"/*.tar.gz; do
        base=$(basename "$archive" .tar.gz)
        tar -kxf "$archive" --directory "$tmp"

        if tar_no_mode_diff "$startdir" "$base" "$archive"; then
            if [[ -d $1 ]]; then
                diff -ur "$startdir/$base" "$tmp/$base" | diff_log "$1" "$base"
            else
                diff -ur "$startdir/$base" "$tmp/$base"
            fi
        fi

        cp -af "$tmp/$base" "$startdir"
    done
}

linef() {
    awk -v "fmt=$1" '{ printf(fmt, $0) }'
}

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

usage() {
    base64 -d <<EOF
ICAgICAgICAgICAgIC4tLX5+LF9fCjotLi4uLiwtLS0tLS0tYH5+Jy5fLicKIGAtLCwsICAsXyAg
ICAgIDsnflUnCiAgXywtJyAsJ2AtX187ICctLS4KIChfLyd+fiAgICAgICcnJycoOwoK
EOF
    printf >&2 'usage: %s [-L path] [-grt] pkgname...\n' "$argv0"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/parseopts.sh

opt_short='L:grt'
opt_long=('log-dir:' 'git' 'print' 'recurse' 'tar')
opt_hidden=('dump-options')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset patch_dir
while true; do
    case "$1" in
	# XXX rename to --patch-dir?
        -L|--log-dir) shift; patch_dir=$(canonicalize_path "$1") ;;
        -r|--recurse) recurse=1 ;;
        -g|--git) mode=git ;;
        -t|--tar) mode=tar ;;
        --print) log=stdout ;;
        --dump-options) printf -- '--%s\n' "${opt_long[@]}" ;
                        printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g' ;
                        exit ;;
        --) shift; break ;;
    esac
    shift
done

tmp=$(mktemp -dt "$argv0".XXXXXXXX)
trap trap_exit EXIT

if ! (($#)); then
    usage
fi

case $log in
    directory)
	# store patches in current directory by default
        if [[ ! -d ${patch_dir:=$startdir} ]]; then
            error "$argv0: '$patch_dir': not a directory"
            exit 21
        fi ;;
    stdout)
        unset patch_dir ;;
esac

# set filters (1)
case $recurse in
    1) deps() { aur depends --pkgbase "$@"; } ;;
    0) deps() { printf '%s\n' "$@"; } ;;
esac

# set filters (2)
case $mode in
    git) uri() { linef "$fmt_git_clone\\n"; } ;;
    tar) uri() { linef "$fmt_snapshot\\n" ; } ;;
esac

# pipeline
deps "$@" | uri | fetch_$mode "$patch_dir"

# vim: set et sw=4 sts=4 ft=sh:
