#!/bin/bash
tmp=$(mktemp -d)
aur repo --root "$tmp" --repo extra --init || exit

aur repo -d extra
(( $? == 66 )) || exit
aur repo -d extra --root "$tmp"
(( $? == 0  )) || exit
aur sync -d extra --root "$tmp" --no-build --no-view aurutils
(( $? == 0  )) || exit
